<a href="https://colab.research.google.com/github/Giustiziero/bell-pepper/blob/initial-testing/tensorflow_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import tensorflow as tf
import numpy as np
import os
import csv

In [3]:
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34, 31]

In [4]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

In [5]:
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

21
22
-108
31
-1
32
34
31


In [6]:
tf_dataset = tf_dataset.filter(lambda x: x>0)

In [7]:
for sales in tf_dataset.as_numpy_iterator():
  print(sales)

21
22
31
32
34
31


In [8]:
for sales in tf_dataset.batch(2):
  print(sales.numpy())

[21 22]
[31 32]
[34 31]


In [13]:
# numpy_array = []
# mnist_df = tf.data.Dataset.list_files("/content/sample_data/mnist_test.csv", shuffle = False)
# with open("/content/sample_data/mnist_test.csv") as csv_file:
#   reader = csv.reader(csv_file)

#   #create array
#   arr = []
#   #append rows to array
#   for i, row in enumerate(reader):
#     arr.append(row)
#   #convert array to numpy array
#   numpy_array = np.array(arr)





In [21]:
### Plant Dataset Test

bell_ds = tf.data.Dataset.list_files('/content/drive/MyDrive/Colab Notebooks/Bell-pepper ML/Bell_pepper/*/*')

In [25]:
for i in bell_ds.take(5):
  print(i.numpy())

b'/content/drive/MyDrive/Colab Notebooks/Bell-pepper ML/Bell_pepper/Pepper__bell___Bacterial_spot/f3fe3173-1b59-404a-b986-133e847f2090___NREC_B.Spot 9054.JPG'
b'/content/drive/MyDrive/Colab Notebooks/Bell-pepper ML/Bell_pepper/Pepper__bell___Bacterial_spot/94c2cf91-17c3-4ee1-b8f2-b20103e1c14f___NREC_B.Spot 9094.JPG'
b'/content/drive/MyDrive/Colab Notebooks/Bell-pepper ML/Bell_pepper/Pepper__bell___Bacterial_spot/e80de14e-9d15-4dc6-b519-6d5af14ba216___JR_B.Spot 8835.JPG'
b'/content/drive/MyDrive/Colab Notebooks/Bell-pepper ML/Bell_pepper/Pepper__bell___Bacterial_spot/3a03526d-0bf4-4898-9f0f-8a9c31afd3eb___JR_B.Spot 3380.JPG'
b'/content/drive/MyDrive/Colab Notebooks/Bell-pepper ML/Bell_pepper/Pepper__bell___Bacterial_spot/5393f88f-ab0b-4b96-bc56-a76eeb106095___JR_B.Spot 8851.JPG'


In [26]:
class_names = ["healthy, deseased"]

In [29]:
image_count = len(bell_ds)
image_count


452

In [62]:
train_size = int(image_count*0.8)

train_ds = bell_ds.take(train_size)
test_ds = bell_ds.skip(train_size)

In [50]:
def get_label(file_path):
  return tf.strings.split(file_path, os.path.sep)[-2]

In [60]:
def process_image(file_path):
  label = get_label(file_path)

  img = tf.io.read_file(file_path)
  img = tf.image.decode_jpeg(img)
  img = tf.image.resize(img, [128, 128])

  return img, label

print(process_image("/content/drive/MyDrive/Colab Notebooks/Bell-pepper ML/Bell_pepper/Pepper__bell___Bacterial_spot/0022d6b7-d47c-4ee2-ae9a-392a53f48647___JR_B.Spot 8964.JPG")[0][0])

tf.Tensor(
[[113.5  101.5  101.5 ]
 [120.   108.   108.  ]
 [131.25 119.25 119.25]
 [110.75  98.75  98.75]
 [122.   110.   110.  ]
 [116.5  104.5  104.5 ]
 [117.75 105.75 105.75]
 [137.   125.   125.  ]
 [124.5  112.5  112.5 ]
 [132.   120.   120.  ]
 [142.   130.   130.  ]
 [123.25 111.25 111.25]
 [134.25 122.25 122.25]
 [138.75 126.75 126.75]
 [130.5  118.5  118.5 ]
 [127.   115.   115.  ]
 [126.25 114.25 114.25]
 [135.25 123.25 123.25]
 [127.75 115.75 115.75]
 [117.25 105.25 105.25]
 [120.   108.   108.  ]
 [124.25 112.25 112.25]
 [118.   106.   106.  ]
 [123.75 111.75 111.75]
 [126.25 114.25 114.25]
 [127.25 115.25 115.25]
 [139.25 127.25 127.25]
 [130.75 118.75 118.75]
 [135.75 123.75 123.75]
 [139.75 127.75 127.75]
 [125.5  113.5  113.5 ]
 [130.25 118.25 118.25]
 [142.   130.   130.  ]
 [126.   114.   114.  ]
 [130.   118.   118.  ]
 [123.   111.   111.  ]
 [113.75 101.75 101.75]
 [123.75 111.75 111.75]
 [120.25 108.25 108.25]
 [111.5   99.5   99.5 ]
 [104.25  92.25  92.25]
 [116

In [67]:
train_ds = train_ds.map(process_image)

for img, label in train_ds.take(1):
  print(img[0][0])

tf.Tensor([143. 132. 130.], shape=(3,), dtype=float32)


In [68]:
def scale(image, label):
  return image/255, label

train_ds = train_ds.map(scale)

for img, label in train_ds.take(1):
   print(img[0][0])

tf.Tensor([0.7970588  0.74215686 0.83235294], shape=(3,), dtype=float32)


In [ ]:
train_ds